---
title: "00_all"
author: "Group 16"
format:
  html:
    embed-resources: true
editor: visual
---

# 00_all

### This is our final Quarto Markdown document with all other documents embedded and rendered

## 01_load

```{r}
quarto::quarto_render("~/projects/group_16_project/R/01_load.qmd")

file.rename(from = "~/projects/group_16_project/R/01_load.html",
             to = "~/projects/group_16_project/results/01_load.html" )
```

## 02_clean

```{r}
quarto::quarto_render("~/projects/group_16_project/R/02_clean.qmd")

file.rename(from = "~/projects/group_16_project/R/02_clean.html",
             to = "~/projects/group_16_project/results/02_clean.html" )
```

## 03_augment

```{r}
quarto::quarto_render("~/projects/group_16_project/R/03_augment.qmd")

file.rename(from = "~/projects/group_16_project/R/03_augment.html",
             to = "~/projects/group_16_project/results/03_augment.html" )
```

## 04_describe

```{r}
quarto::quarto_render("~/projects/group_16_project/R/04_describe.qmd")

file.rename(from = "~/projects/group_16_project/R/04_describe.html",
             to = "~/projects/group_16_project/results/04_describe.html" )
```

## 05_analysis_1

```{r}
quarto::quarto_render("~/projects/group_16_project/R/05_analysis_1.qmd")

file.rename(from = "~/projects/group_16_project/R/05_analysis_1.html",
             to = "~/projects/group_16_project/results/05_analysis_1.html" )
```

## 06_analysis_2

```{r}
quarto::quarto_render("~/projects/group_16_project/R/06_analysis_2.qmd")

file.rename(from = "~/projects/group_16_project/R/06_analysis_2.html",
             to = "~/projects/group_16_project/results/06_analysis_2.html" )
```

## 07_analysis_3

```{r}
quarto::quarto_render("~/projects/group_16_project/R/07_analysis_3.qmd")

file.rename(from = "~/projects/group_16_project/R/07_analysis_3.html",
             to = "~/projects/group_16_project/results/07_analysis_3.html" )
```
