# Cleaning the data

1.  Load all important library's

```{r}
library(tidyverse)
```

```{r}
#| message: false
data <- read_tsv("../data/01_dat_load.tsv", na= c("", "NA", "N/A", "missing", "?"))
data <- drop_na(data)
```

```{r}
colnames(data) <- c('age','sex','cp','trestbps','chol','fbs','restecg','thalach','exang','oldpeak','slope','ca','thal','num') 
```

To clean data

```{r}
data <- data |> 
  mutate(cp = case_when
         (cp == '1' ~ 'typical angina',
            cp == '2' ~ 'atypical angina',
            cp == '3' ~ 'non-anginal pain',
            cp == '4' ~ 'asymptomatic')) |> 
  mutate(sex = case_when(
    sex == '1' ~ 'male',
    sex == '0' ~ 'female'
  )) |> 
  mutate(exang = case_when(
    exang == '1' ~ 'yes',
    exang == '0' ~ 'no'
  )) |> 
  mutate(slope = case_when(
    slope == '1' ~ 'upsloping',
    slope == '2' ~ 'flat',
    slope == '3' ~ 'downsloping'
  )) |> 
  mutate(fbs = case_when(
    fbs == '1' ~ 'greater than 120mg/ml',
    fbs == '0' ~ 'lower than 120mg/ml'
  )) |> 
  mutate(restecg = case_when(
    restecg == '0' ~ 'normal',
    restecg == '1' ~ 'ST-T wave abnormality',
    restecg == '2' ~ 'left ventricular hypertrophy'
  )) |> 
  mutate(thal = case_when(
    thal == '3' ~ 'normal',
    thal == '6' ~ 'fixed defect',
    thal == '7' ~ 'reversable defect'
  )) 
```

save the cleaned data

```{r}
readr::write_tsv(data, "../data/02_dat_clean.tsv")
```
